algoritmo "semnome"
// Função :
// Autor :
// Data : 28/01/25
// Seção de Declarações
var
idade, ano, apto:real
inicio
escreva("Em que anos estamos? ")
Leia(ano)

escreva("Qual o ano de nascimeto do cliente? ")
Leia(idade)

apto <- ano - idade

Se (apto >= 18) entao
   Escreval("A idade do cliente é: ", apto)
   escreval("Ele é apto para dirigir!")
SeNao
   Escreval("A idade do cliente é: ", apto)
   escreval("o cliente não é apto para dirigir!")
FimSe
fimalgoritmo
